version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.2
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'

    PYTHONPATH: /opt/retail_project
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins

    - ./:/opt/retail_project:ro
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    - postgres

services:
  # POSTGRESQL DATABASE
  retail_postgres:
    image: postgres:15-alpine
    container_name: retail_postgres
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_password
      POSTGRES_DB: nova_retail_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U retail_user -d nova_retail_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - retail_network

  # AIRFLOW POSTGRES (for Airflow metadata)

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - retail_network

  # AIRFLOW SERVICES
  airflow-webserver:
    <<: *airflow-common
    container_name: retail_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - retail_network

  airflow-scheduler:
    <<: *airflow-common
    container_name: retail_airflow_scheduler
    command: scheduler
    networks:
      - retail_network

  airflow-init:
    <<: *airflow-common
    container_name: retail_airflow_init
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    networks:
      - retail_network
    # Airflow UI: http://localhost:8080

networks:
  retail_network:
    name: retail_network

volumes:
  postgres_data:
    name: nova_retail_postgres_data
  airflow_db_data:
    name: nova_retail_airflow_db
